vim.opt.number = true         -- show numbers
vim.o.background = 'dark'     -- bg
vim.opt.hlsearch = true       -- highlight search results
vim.opt.tabstop = 2           -- tab size
vim.opt.shiftwidth = 0        -- autoindent size
vim.opt.expandtab = true      -- spaces
vim.opt.swapfile = false      -- no backup files
vim.opt.mouse = "i"           -- enable mouse on insert
vim.opt.showmatch = true      -- highlights matching bracket
vim.opt.termguicolors = true  -- for themes
vim.opt.hidden = true         -- multiple buffers
vim.opt.showmode = false      -- remove insert msg
vim.opt.encoding = 'utf-8'    -- encoding
vim.opt.cmdheight = 2         -- better msg readability