#!/bin/bash

source "$CONFIG_DIR/globals.sh"
source "$CONFIG_DIR/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

# bar appearance
sketchybar --bar height=25 \
                 blur_radius=30 \
                 y_offset=5 \
                 position=top \
                 sticky=off \
                 padding_left=15 \
                 padding_right=15 \
                 color=$BAR_COLOR \

# change defaults
sketchybar --default icon.font="JetBrainsMono Nerd Font:Bold:$ICON_FONT_SIZE.0" \
                     label.font="JetBrainsMono Nerd Font:Bold:$FONT_SIZE.0" \
                     label.color=$BG_LABEL_COLOR_ALT \
                     background.color=$BG_COLOR \
                     background.corner_radius=5 \
                     background.height=24 \
                     background.border_width=1 \
                     background.border_color=$BG_LABEL_COLOR_ALT \

                     # label.padding_left=4 \
                     # label.padding_right=4 \

# mission control spaces
# add left items
# source $ITEM_DIR/os.sh
# source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# right side of notch items
source $ITEM_DIR/media.sh

# add right items
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/network.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
# source $ITEM_DIR/cpu.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

